# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='昵称')),
                ('sex', models.CharField(choices=[('F', '男'), ('M', '女')], max_length=2, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('head_img', models.CharField(choices=[('head-1.png', '男士1'), ('head-3.png', '男士2'), ('head-4.png', '男士3'), ('head-2.png', '女士1'), ('head-5.png', '女士2'), ('head-6.png', '女士3')], default='head-1.png', max_length=30, verbose_name='头像')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='签名')),
                ('friends', models.ManyToManyField(blank=True, null=True, related_name='_loginuser_friends_+', to='chatroom.LoginUser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=100, verbose_name='用户分组名')),
                ('isdefault', models.IntegerField(default=0)),
                ('members', models.ManyToManyField(related_name='usergroup_member', to='chatroom.LoginUser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mygroup', to='chatroom.LoginUser')),
            ],
        ),
        migrations.CreateModel(
            name='WebGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='群组名')),
                ('brief', models.CharField(blank=True, max_length=200, null=True, verbose_name='群组备注')),
                ('max_members', models.IntegerField()),
                ('admins', models.ManyToManyField(blank=True, null=True, related_name='webgroup_admins', to='chatroom.LoginUser')),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='webgroup_member', to='chatroom.LoginUser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatroom.LoginUser')),
            ],
        ),
    ]
