# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=16, verbose_name='用户名')),
                ('upasswd', models.CharField(max_length=16, verbose_name='密码')),
                ('uemail', models.CharField(max_length=32, verbose_name='邮箱')),
                ('uyoubian', models.CharField(max_length=6, verbose_name='邮编')),
                ('uaddress', models.CharField(max_length=100, verbose_name='地址')),
                ('uphone', models.CharField(max_length=11, verbose_name='手机')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('r_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
        ),
    ]
