# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='upasswd',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
    ]
