# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0002_auto_20170622_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='shouname',
            field=models.CharField(default=1233, max_length=16, verbose_name='收件人'),
            preserve_default=False,
        ),
    ]
