# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0003_userinfo_shouname'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='conment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=120, verbose_name='评论')),
                ('r_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='商品名称')),
                ('description', models.CharField(max_length=200, verbose_name='商品描述')),
                ('detail', models.TextField(max_length=500, verbose_name='详情')),
                ('standard', models.CharField(default='500g', max_length=10, verbose_name='规格')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='单价')),
                ('hots', models.IntegerField(default=0, verbose_name='热度')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('r_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.category')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uname',
            field=models.CharField(max_length=16, unique=True, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='product',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.userInfo'),
        ),
        migrations.AddField(
            model_name='conment',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.product'),
        ),
        migrations.AddField(
            model_name='conment',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.userInfo'),
        ),
    ]
