# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0004_auto_20170623_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('r_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.userInfo')),
            ],
        ),
        migrations.CreateModel(
            name='detail_ctg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.category')),
            ],
        ),
        migrations.CreateModel(
            name='recent_views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.userInfo')),
            ],
        ),
    ]
