# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0005_cart_detail_ctg_recent_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='单价')),
                ('classification', models.IntegerField(max_length=1)),
                ('r_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.userInfo')),
            ],
        ),
    ]
