# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon_url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
