# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0008_auto_20170623_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detail_ctg',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='icon_url',
            field=models.ImageField(null=True, upload_to='productsIcon/'),
        ),
    ]
