# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0010_auto_20170624_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderInfo',
            fields=[
                ('orderNumber', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='总价')),
                ('isDelete', models.BooleanField(default=False)),
                ('isPaid', models.BooleanField(default=False, verbose_name='是否付款')),
                ('r_time', models.DateTimeField(auto_now=True, verbose_name='生成时间')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.userInfo')),
            ],
        ),
        migrations.CreateModel(
            name='orderProInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='单价')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.orderInfo')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='uid',
        ),
        migrations.AlterUniqueTogether(
            name='recent_views',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='recent_views',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='recent_views',
            name='uid',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='recent_views',
        ),
    ]
